language: ruby
version: 1.9.3
bundler_args: --without development
before_script:
- sh -e /etc/init.d/xvfb start
script: PADRINO_ENV=travis bundle exec rake

deploy:
  provider: heroku
  api_key:
    secure: YDjDiARMnUUl5/uUVmB4r21IXO1k2t8SqVQW2vcPp3eQZNqbapjCGFyCdPTU9WhQavmnI7q3EpY767e7psEIWWJDT4MfOvsieBW+jfub4gjbUkPBDVITWgGmQjPo+xcSU0390axATCiH/T9xVM5rfCggcejX/OS/W07z1U3j2+A=
  app: ixchel
  on:
    repo: lrrinaudo/ixchel
